# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hwgrpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hwgrpc.proto',
  package='hwgrpc',
  syntax='proto3',
  serialized_pb=_b('\n\x0chwgrpc.proto\x12\x06hwgrpc\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t2A\n\x07Greeter\x12\x36\n\x08SayHello\x12\x14.hwgrpc.HelloRequest\x1a\x12.hwgrpc.HelloReply\"\x00\x42\x37\n\x17\x63om.codemodus.io.hwgrpcB\x0fHelloWorldProtoP\x01Z\x03idl\xa2\x02\x03HLWb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_HELLOREQUEST = _descriptor.Descriptor(
  name='HelloRequest',
  full_name='hwgrpc.HelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='hwgrpc.HelloRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=52,
)


_HELLOREPLY = _descriptor.Descriptor(
  name='HelloReply',
  full_name='hwgrpc.HelloReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='hwgrpc.HelloReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=83,
)

DESCRIPTOR.message_types_by_name['HelloRequest'] = _HELLOREQUEST
DESCRIPTOR.message_types_by_name['HelloReply'] = _HELLOREPLY

HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), dict(
  DESCRIPTOR = _HELLOREQUEST,
  __module__ = 'hwgrpc_pb2'
  # @@protoc_insertion_point(class_scope:hwgrpc.HelloRequest)
  ))
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), dict(
  DESCRIPTOR = _HELLOREPLY,
  __module__ = 'hwgrpc_pb2'
  # @@protoc_insertion_point(class_scope:hwgrpc.HelloReply)
  ))
_sym_db.RegisterMessage(HelloReply)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\027com.codemodus.io.hwgrpcB\017HelloWorldProtoP\001Z\003idl\242\002\003HLW'))
import abc
import six
from grpc.beta import implementations as beta_implementations
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities

class BetaGreeterServicer(six.with_metaclass(abc.ABCMeta, object)):
  """<fill me in later!>"""
  @abc.abstractmethod
  def SayHello(self, request, context):
    raise NotImplementedError()

class BetaGreeterStub(six.with_metaclass(abc.ABCMeta, object)):
  """The interface to which stubs will conform."""
  @abc.abstractmethod
  def SayHello(self, request, timeout):
    raise NotImplementedError()
  SayHello.future = None

def beta_create_Greeter_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
  import hwgrpc_pb2
  import hwgrpc_pb2
  request_deserializers = {
    ('hwgrpc.Greeter', 'SayHello'): hwgrpc_pb2.HelloRequest.FromString,
  }
  response_serializers = {
    ('hwgrpc.Greeter', 'SayHello'): hwgrpc_pb2.HelloReply.SerializeToString,
  }
  method_implementations = {
    ('hwgrpc.Greeter', 'SayHello'): face_utilities.unary_unary_inline(servicer.SayHello),
  }
  server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
  return beta_implementations.server(method_implementations, options=server_options)

def beta_create_Greeter_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
  import hwgrpc_pb2
  import hwgrpc_pb2
  request_serializers = {
    ('hwgrpc.Greeter', 'SayHello'): hwgrpc_pb2.HelloRequest.SerializeToString,
  }
  response_deserializers = {
    ('hwgrpc.Greeter', 'SayHello'): hwgrpc_pb2.HelloReply.FromString,
  }
  cardinalities = {
    'SayHello': cardinality.Cardinality.UNARY_UNARY,
  }
  stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
  return beta_implementations.dynamic_stub(channel, 'hwgrpc.Greeter', cardinalities, options=stub_options)
# @@protoc_insertion_point(module_scope)
